repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.9
    hooks:
      - id: ruff-check
      - id: ruff-format

  - repo: local
    hooks:
      - id: ty-check
        name: Check type
        entry: ty check
        language: system
        types_or: [python]
